on:
  push:
    tags:
      - '*'
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run package
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.vsix"
          bodyFile: "RELEASE.md"
          token: ${{ secrets.GITHUB_TOKEN }}